### PR TITLE
feat: delete multiple files at once

### PR DESCRIPTION
**Pull request by Ian2012**
### Description

This PR upgrades the delete_file endpoint to accept a list of asset keys to delete

### Testing instructions

1. Go to studio and edit the componente
2. Add some images
image
3. Click on the delete button hovering the images
4. Verify the image is deleted
image

**Merge checklist:**
Check off if complete *or* not applicable:
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Fixup commits are squashed away
- [ ] Unit tests added/updated
- [ ] Manual testing instructions provided
- [ ] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

**Merge checklist:**
Check off if complete *or* not applicable:
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Fixup commits are squashed away
- [ ] Unit tests added/updated
- [ ] Manual testing instructions provided
- [ ] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

### CODE REVIEW

**Comment by mariajgrimaldi** [comment]
Remember to add the team as a reviewer. And add testing instructions to the PR cover letter. Thanks!

**Comment by BryanttV** [comment]
LGTM!

**Review by BryanttV — APPROVED** [review]

**Comment by mariajgrimaldi** [comment]
Thanks for this change. How do I select multiple images? Can that be done with the current UI?

**Comment by Ian2012** [comment]
Not, it cannot.

**Review by mariajgrimaldi — APPROVED** [review]
LGTM! I guess we're implementing sending multiple images for deletion with the save functionality.

**Pull request merged**
